### ISSUE TITLE
Cannot build provided template project

### ISSUE THREAD

**Issue by jcornaz** [marcoferrer/kroto-plus#29]
Hi, 

The instructions given here: https://github.com/marcoferrer/kroto-plus/tree/master/example-grpc-client-server#quick-start:

```
git clone https://github.com/marcoferrer/kotlin-coroutines-gRPC-template && \
cd kotlin-coroutines-gRPC-template && \
./gradlew run
```

produce the following output:

```
Cloning into 'kotlin-coroutines-gRPC-template'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 57 (delta 18), reused 44 (delta 9), pack-reused 0
Unpacking objects: 100% (57/57), done.
e: ~/Workspace/kotlin-coroutines-gRPC-template/api/build/generated/source/proto/main/coroutines/io/grpc/examples/helloworld/GreeterCoroutineGrpc.kt: (25, 25): Unresolved reference: Generated
e: ~/Workspace/kotlin-coroutines-gRPC-template/api/build/generated/source/proto/main/coroutines/io/grpc/examples/helloworld/GreeterCoroutineGrpc.kt: (37, 2): Unresolved reference: Generated
> Task :api:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':api:compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
6 actionable tasks: 6 executed
```

**Comment by marcoferrer** [comment]
What it looks like to me is an unresolved reference to `javax.annotation.Generated`.

Which java version are you using? 

I think your issue might be somewhat related to this [grpc-issue](https://github.com/grpc/grpc-java/issues/3633)

**Comment by marcoferrer** [comment]
If you are using jdk 9+ then you may experience issues with `javax.annotation` in general. The suggested fix mentioned [here](https://github.com/grpc/grpc-java/issues/4725) is adding the dependency explicitly. 

```groovy
compileOnly "javax.annotation:javax.annotation-api:1.2"
```

Thanks for pointing this out. Ill be sure to update the templates

**Comment by jcornaz** [comment]
Yes I am using a jdk 10.

I'll try the fix. Thanks for updating the template.

**Comment by marcoferrer** [comment]
I’m going to close out this issue. If you run into anymore issues with running the template project fell free to reopen. On a side note, when I updated the templates I removed a few code smells for ambiguous scope resolution.

**Comment by jcornaz** [comment]
OK, thanks @marcoferrer
