### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by essh** [marcoferrer/kroto-plus#3]
Would it be possible to get the latest version of this project pushed up to Maven Central? The README says that it is available on mavenCentral() but the latest version I see there is 0.1.1.

Thanks.

**Comment by marcoferrer** [comment]
Thanks for the heads up. I just realized there was an issue with the deploy process. Ill get that fixed in a few and update here.

**Comment by marcoferrer** [comment]
Latest artifacts are up now. Free to let me know if there are anymore issues
