### ISSUE TITLE
Add support for malformed protobuf filenames

### ISSUE THREAD

**Issue by marcoferrer** [marcoferrer/kroto-plus#56]
Not all existing protobuf files follow the convention of snake case for file names. We should ensure that we support any non erroneous format supported by the java and grpc protoc plugins.

**Comment by marcoferrer** [comment]
CC: @AlexeySoshin

**Comment by AlexeySoshin** [comment]
Do you want to take it, or should I?

**Comment by marcoferrer** [comment]
You’re more than welcome to pick it up. Thanks again for bringing it to my attention. 
We will need to verify what’s is considered valid by protoc-gen-java and match that. 

Test proto files can be added to the `test-api` module. They can then have simple assertions added in the `generator-tests` module. Nothing fancy is needed since compilation will verify if the out is correct. That module will contain existing examples. 

If you run into any issues of have any questions feel free to reach out
