### ISSUE TITLE
Typo in config message name

### ISSUE THREAD

**Issue by RdeWilde** [marcoferrer/kroto-plus#57]
https://github.com/marcoferrer/kroto-plus/blob/720fdf37db11bfa9c7d433e2d83eac4d55746b4f/protoc-gen-kroto-plus/src/main/proto/krotoplus/compiler/config.proto#L121

**Comment by marcoferrer** [comment]
Thanks for reporting this. This is a relatively safe change to make. Its up for grabs if you'd like, else I'll get a PR up later tonight.
