### ISSUE TITLE
Failed to generate maven coroutines proto for jvm8 classifier in Ubuntu

### ISSUE THREAD

**Issue by brvith** [marcoferrer/kroto-plus#80]
It is working fine in development (Mac OS). But in Ubuntu environment, I get the below errors.  I checked maven repositories all plugin jars are present. Is there any special configuration, I need to make.

kroto-plus.version = 0.5.0

` 
<execution>
                        <id>grpc-coroutines</id>
                        <goals>
                            <goal>compile-custom</goal>
                        </goals>
                        <configuration>
                            <pluginId>kroto-plus</pluginId>
                            <pluginArtifact>
                                com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:${kroto-plus.version}:jar:jvm8
                            </pluginArtifact>
                            <pluginParameter>ConfigPath=${project.basedir}/krotoPlusConfig.asciipb</pluginParameter>
                        </configuration>
                    </execution>
`

Unbuntu Info:

`
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.4
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 4
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 16.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
`

Failed logs:
`
[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile-custom (grpc-coroutines) on project blueprint-proto: Unable to resolve artifact: Missing:
[ERROR] ----------
[ERROR] 1) com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:jar:jvm8:0.5.0
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.github.marcoferrer.krotoplus -DartifactId=protoc-gen-kroto-plus -Dversion=0.5.0 -Dclassifier=jvm8 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.github.marcoferrer.krotoplus -DartifactId=protoc-gen-kroto-plus -Dversion=0.5.0 -Dclassifier=jvm8 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]   	1) org.onap.ccsdk.cds.controllerblueprints:blueprint-proto:jar:0.7.0-SNAPSHOT
[ERROR]   	2) com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:jar:jvm8:0.5.0
[ERROR] 
[ERROR] ----------
[ERROR] 1 required artifact is missing.
`

**Comment by marcoferrer** [comment]
There shouldn’t be any special configuration required for usage in Linux environments. Have you verified that your maven repo is accessible from the Ubuntu machine? Also  are you able to verify that this artifact exists as well? `org.onap.ccsdk.cds.controllerblueprints:blueprint-proto:jar:0.7.0-SNAPSHOT`

**Comment by brvith** [comment]
Yes, You are right. Some thing is with connection and delays. Thanks for your response.
