### ISSUE TITLE
compile-custom fails on Windows 10

### ISSUE THREAD

**Issue by kasingal** [marcoferrer/kroto-plus#83]
It works on Ubuntu, MacOS but fails on Windows 10.
Using below execution configutration (with kroto-plus.version = 0.5.0)

```
<execution>
    <id>grpc-coroutines</id>
    <goals>
        <goal>compile-custom</goal>
    </goals>
    <configuration>
        <pluginId>kroto-plus</pluginId>
        <pluginArtifact>com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:${kroto-plus.version}:jar:jvm8</pluginArtifact>
        <pluginParameter>ConfigPath=./krotoPlusConfig.asciipb</pluginParameter>
    </configuration>
</execution>
```

Windows Info:
```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 10.0
[INFO] os.detected.version.major: 10
[INFO] os.detected.version.minor: 0
[INFO] os.detected.classifier: windows-x86_64
```

Failed Error Logs:
```
[INFO] --- protobuf-maven-plugin:0.6.1:compile-custom (grpc-coroutines) @ blueprint-proto ---
[INFO] Compiling 4 proto file(s) to C:\git\modules\target\generated-sources\protobuf\kroto-plus
[ERROR] PROTOC FAILED: --kroto-plus_out: protoc-gen-kroto-plus: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

[ERROR] C:\git\modules\components\proto-definition\proto\CommandExecutor.proto [0:0]: --kroto-plus_out: protoc-gen-kroto-plus: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by marcoferrer** [comment]
Sorry about the delay ed response. Im sorry but yes there are currently issues when using the plugin within windows environments. It is discussed extensively in https://github.com/marcoferrer/kroto-plus/issues/6 

The quickest short term workaround is outlined in this comment https://github.com/marcoferrer/kroto-plus/issues/6#issuecomment-505099688

There is a long term stable solution currently slated for the next release is this PR https://github.com/marcoferrer/kroto-plus/pull/87

**Comment by mattdkerr** [comment]
Thanks @marcoferrer-- I left a single comment on the PR. Otherwise it looks good to me.

**Comment by marcoferrer** [comment]
@mattdkerr No worries. Thanks again for reporting. The PRs been merged and I published a snapshot of `0.6.0`

Please let me know if you run into anymore issues.  I’m really happy to get this resolved. The issues with windows compatibility have been bugging me for a while.

**Comment by mattdkerr** [comment]
I changed the line to look like:
```
artifact = "com.github.marcoferrer.krotoplus:protoc-gen-kroto-plus:$krotoPlusVersion"
```
and then I get successful `generateProto` and `compileJava` sequences. Thanks!

**Comment by marcoferrer** [comment]
Awesome thanks for the confirmation! The goal is to release later this week.

**Comment by mattdkerr** [comment]
Is there documentation for the coroutine BiDi server functions? I'm trying to do it like the example project, but I only see ClientBidiChannel stuff not ReceiveChannel/SendChannel. I'm not sure if this is a bug with this new method on Windows, or my problem implementing.

**Comment by jebbench** [comment]
Using `0.6.0-SNAPSHOT` and removing `:jvm8@jar` from the artifact in my protobuf config got this working on Windows for me.

My full protobuf config is:
```
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:$protobuf_version"
    }

    //noinspection GroovyAssignabilityCheck
    plugins {
        grpc { artifact = "io.grpc:protoc-gen-grpc-java:$grpc_version" }
        coroutines {
            artifact = "com.github.marcoferrer.krotoplus:protoc-gen-grpc-coroutines:$krotoplus_version"
        }
    }

    generateProtoTasks {
        all().each{ task ->
            task.plugins {
                grpc {}
                coroutines {}
            }
        }
    }
}
```

**Comment by marcoferrer** [comment]
With `0.6.0` released, there is now an executable windows artifact available.
