### ISSUE TITLE
Forward documentation for stubs

### ISSUE THREAD

**Issue by metarag** [marcoferrer/kroto-plus#85]
We can document our RPCs in the proto files like 
```protobuf
service GreeterService {
    /* Simply echoes the name prefixed with Hi */
    rpc SayHello (HelloRequest) returns (HelloResponse);
}
```

The stubs generated by grpc-java contain this documentation as javadocs. However, the coroutine stub generated by kroto plus is missing this documentation.

**Comment by marcoferrer** [comment]
This should be an easy fix. Thanks for bringing it up! I'll make sure to get into the upcoming release.
